"""users table init

Revision ID: 15ba36047ce1
Revises: 
Create Date: 2024-09-12 16:38:10.925445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15ba36047ce1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.drop_table('_prisma_migrations')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('User_email_key')

    op.drop_table('User')
    op.drop_table('Role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=191), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('User',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('lang', mysql.VARCHAR(length=191), server_default=sa.text("'ua'"), nullable=False),
    sa.Column('roleId', mysql.VARCHAR(length=191), nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], name='User_roleId_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index('User_email_key', ['email'], unique=True)

    op.create_table('_prisma_migrations',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('checksum', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('finished_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('migration_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('logs', mysql.TEXT(), nullable=True),
    sa.Column('rolled_back_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('started_at', mysql.DATETIME(fsp=3), server_default=sa.text('current_timestamp(3)'), nullable=False),
    sa.Column('applied_steps_count', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
